name: Build Xamarin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  buildios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
#       - name: Select default Xamarin bundle to 6_12_6
#         run: |
#           XAMARIN_SDK=6_12_6
#           $VM_ASSETS/select-xamarin-sdk.sh $XAMARIN_SDK

#       - name: Set default Xcode 12.3
#         run: |
#           XCODE_ROOT=/Applications/Xcode_12.3.0.app
#           echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
#           sudo xcode-select -s $XCODE_ROOT

      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: nuget restore XamCast.sln

      - name: Build
        run: msbuild XamCast.iOS/XamCast.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
        
  buildandroid:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
#       - name: Select default Xamarin bundle to 6_12_6
#         run: |
#           XAMARIN_SDK=6_12_6
#           $VM_ASSETS/select-xamarin-sdk.sh $XAMARIN_SDK

      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: nuget restore XamCast.sln

      - name: Build
        run: msbuild XamCast.Android/XamCast.Android.csproj /t:PackageForAndroid /p:Configuration=Debug
  
